services:
  backend:
    build: ./backend
    command: npm run start:dev
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next_cache:/app/.next
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend_node_modules: {}
  frontend_node_modules: {}
  frontend_next_cache: {}
