version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_agent_manager_backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    # restart: unless-stopped # Optional: Auto-restart policy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_agent_manager_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    networks:
      - app-network
    depends_on:
      - backend # Ensure backend starts before frontend if needed
    # restart: unless-stopped # Optional: Auto-restart policy

networks:
  app-network:
    driver: bridge
